// 2025年盐城工学院普通类专业录取分数线汇总
// 物理类最低投档线：506分（位次154,519）
// 历史类最低投档线：533分（位次31,664）
// 中外合作办学最低投档线：484分（位次183,221）
// 数据来源：图片中的招生简章表格

const MAJORS = [

  // ========== 物理类 · 专业组03（高分段） ==========
  {
    id: 'electrical-engineering',
    name: '电气工程及其自动化',
    college: '电气与信息工程学院',
    type: 'physics',
    minScore: 539,
    avgScore: 543,
    maxScore: 552,
    plan: 120,
    rank: 106681,
    tags: ['03专业组', '王牌工科', '热门专业'],
    hotLevel: 5,
    description: '培养掌握电气工程基本理论和专业知识，能在电力系统、电气设备制造、新能源发电等领域从事设计、生产、管理的高级工程技术人才。',
    features: ['王牌工科专业', '电力系统方向', '就业面广'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、电路分析' },
      { semester: '第2学期', name: '模拟电子技术、线性代数' },
      { semester: '第3学期', name: '数字电子技术、电机与拖动' },
      { semester: '第4学期', name: '电力电子技术、自动控制原理' },
      { semester: '第5学期', name: '电力系统分析、单片机原理' },
      { semester: '第6学期', name: '电气控制与PLC、高电压技术' },
      { semester: '第7学期', name: '专业实习、新能源发电技术' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '毕业生广泛就业于国家电网、发电企业、电气设备制造企业、科研院所。',
    teachers: '师资力量雄厚，教授、副教授占比高。',
    salary: '毕业五年平均月薪约 7000-13000元'
  },
  {
    id: 'accounting-physics',
    name: '会计学',
    college: '经济管理学院',
    type: 'physics',
    minScore: 534,
    avgScore: 538,
    maxScore: 547,
    plan: 80,
    rank: 113740,
    tags: ['03专业组', '有色觉要求', '经管类热门'],
    hotLevel: 5,
    description: '培养掌握会计学基本理论和方法，能在企事业单位、政府部门从事会计核算、财务管理、审计等工作的高级专门人才。',
    features: ['高分热门专业', '注册会计师方向', '稳定就业'],
    courses: [
      { semester: '第1学期', name: '高等数学、管理学原理、基础会计' },
      { semester: '第2学期', name: '经济学原理、统计学' },
      { semester: '第3学期', name: '中级财务会计、财务管理' },
      { semester: '第4学期', name: '成本会计、管理会计' },
      { semester: '第5学期', name: '高级财务会计、审计学' },
      { semester: '第6学期', name: '会计信息系统、财务分析' },
      { semester: '第7学期', name: '专业实习、会计综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '主要就业于各类企业、金融机构、会计师事务所、政府部门。',
    teachers: '专业教师具有丰富的会计实践经验。',
    salary: '毕业五年平均月薪约 6000-11000元'
  },
  {
    id: 'electronics-information',
    name: '电子信息工程',
    college: '电气与信息工程学院',
    type: 'physics',
    minScore: 533,
    avgScore: 537,
    maxScore: 546,
    plan: 80,
    rank: 115116,
    tags: ['03专业组', '无限制', '电子信息'],
    hotLevel: 5,
    description: '培养掌握电子信息工程基本理论和技术，能在电子设备、通信系统、嵌入式系统等领域从事设计、开发、应用的高级工程技术人才。',
    features: ['电子信息方向', '通信与嵌入式应用', '信息产业热门'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、电路分析' },
      { semester: '第2学期', name: '模拟电子技术、C语言程序设计' },
      { semester: '第3学期', name: '数字电子技术、信号与系统' },
      { semester: '第4学期', name: '通信原理、单片机原理' },
      { semester: '第5学期', name: '数字信号处理、嵌入式系统' },
      { semester: '第6学期', name: '物联网技术、FPGA设计' },
      { semester: '第7学期', name: '专业实习、无线通信技术' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于电子信息企业、通信企业、互联网企业、科研院所。',
    teachers: '专业教师具有电子信息行业背景。',
    salary: '毕业五年平均月薪约 6500-12000元'
  },
  {
    id: 'automation',
    name: '自动化',
    college: '电气与信息工程学院',
    type: 'physics',
    minScore: 529,
    avgScore: 533,
    maxScore: 542,
    plan: 80,
    rank: 120768,
    tags: ['03专业组', '无限制', '控制科学'],
    hotLevel: 4,
    description: '培养掌握自动化基本理论和技术，能在工业自动化、智能制造、过程控制等领域从事设计、开发、运行、管理的高级工程技术人才。',
    features: ['自动化方向', '工业控制应用', '制造业热门'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、电路分析' },
      { semester: '第2学期', name: '模拟电子技术、C语言程序设计' },
      { semester: '第3学期', name: '数字电子技术、电机与拖动' },
      { semester: '第4学期', name: '自动控制原理、单片机原理' },
      { semester: '第5学期', name: '过程控制、运动控制、PLC技术' },
      { semester: '第6学期', name: '工业机器人、组态软件' },
      { semester: '第7学期', name: '专业实习、综合自动化系统' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于制造业企业、自动化企业、工业机器人企业。',
    teachers: '专业教师具有自动化工程实践经验。',
    salary: '毕业五年平均月薪约 6000-11000元'
  },
  {
    id: 'artificial-intelligence',
    name: '人工智能',
    college: '计算机学院',
    type: 'physics',
    minScore: 528,
    avgScore: 532,
    maxScore: 541,
    plan: 80,
    rank: 122199,
    tags: ['03专业组', '有色觉要求', '新兴专业', '热门工科'],
    hotLevel: 5,
    description: '培养掌握人工智能基本理论和技术，能在机器学习、深度学习、智能系统等领域从事研究、开发、应用的高级工程技术人才。',
    features: ['人工智能方向', '机器学习应用', '新兴热门专业'],
    courses: [
      { semester: '第1学期', name: '高等数学、Python程序设计' },
      { semester: '第2学期', name: '线性代数、概率论与数理统计' },
      { semester: '第3学期', name: '数据结构、算法设计' },
      { semester: '第4学期', name: '机器学习基础、数据挖掘' },
      { semester: '第5学期', name: '深度学习、神经网络' },
      { semester: '第6学期', name: '计算机视觉、自然语言处理' },
      { semester: '第7学期', name: '智能系统、企业项目实战' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于人工智能企业、互联网公司、大数据企业、科研院所。',
    teachers: '专业教师紧跟人工智能前沿技术。',
    salary: '毕业五年平均月薪约 7000-14000元'
  },
  {
    id: 'computer-science',
    name: '计算机科学与技术',
    college: '计算机学院',
    type: 'physics',
    minScore: 528,
    avgScore: 532,
    maxScore: 541,
    plan: 100,
    rank: 122199,
    tags: ['03专业组', '有色觉要求', '传统优势', '热门工科'],
    hotLevel: 5,
    description: '培养掌握计算机科学与技术基本理论，能在软件开发、系统设计、网络技术等领域从事研究、开发、管理的高级工程技术人才。',
    features: ['计算机科学方向', '软件开发应用', '传统优势专业'],
    courses: [
      { semester: '第1学期', name: '高等数学、C语言程序设计' },
      { semester: '第2学期', name: '离散数学、数据结构' },
      { semester: '第3学期', name: '计算机组成原理、操作系统' },
      { semester: '第4学期', name: '计算机网络、数据库原理' },
      { semester: '第5学期', name: '编译原理、软件工程' },
      { semester: '第6学期', name: 'Java高级编程、Web开发' },
      { semester: '第7学期', name: '人工智能、云计算' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于互联网企业、软件公司、大型企业IT部门、科研院所。',
    teachers: '专业教师具有丰富的软件开发经验。',
    salary: '毕业五年平均月薪约 7000-14000元'
  },
  {
    id: 'software-engineering',
    name: '软件工程',
    college: '计算机学院',
    type: 'physics',
    minScore: 528,
    avgScore: 532,
    maxScore: 541,
    plan: 80,
    rank: 122199,
    tags: ['03专业组', '有色觉要求', '软件开发', '热门工科'],
    hotLevel: 5,
    description: '培养掌握软件工程基本理论和方法，能在软件企业从事软件设计、开发、测试、项目管理的高级工程技术人才。',
    features: ['软件工程方向', '软件测试与管理', '软件开发热门'],
    courses: [
      { semester: '第1学期', name: '高等数学、C语言程序设计' },
      { semester: '第2学期', name: '数据结构、Java程序设计' },
      { semester: '第3学期', name: '操作系统、数据库原理' },
      { semester: '第4学期', name: '计算机网络、面向对象分析设计' },
      { semester: '第5学期', name: '软件工程、软件测试技术' },
      { semester: '第6学期', name: '软件架构设计、项目管理' },
      { semester: '第7学期', name: '企业项目实战' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于软件公司、互联网企业、大型企业IT部门。',
    teachers: '专业教师具有软件开发和项目管理经验。',
    salary: '毕业五年平均月薪约 7000-13000元'
  },
  {
    id: 'network-engineering',
    name: '网络工程',
    college: '计算机学院',
    type: 'physics',
    minScore: 527,
    avgScore: 531,
    maxScore: 540,
    plan: 80,
    rank: 123540,
    tags: ['03专业组', '有色觉要求', '网络技术', '热门工科'],
    hotLevel: 4,
    description: '培养掌握网络工程基本理论和技术，能在网络系统设计、网络安全、网络管理等领域从事设计、开发、运维的高级工程技术人才。',
    features: ['网络工程方向', '网络安全应用', '网络运维与设计'],
    courses: [
      { semester: '第1学期', name: '高等数学、C语言程序设计' },
      { semester: '第2学期', name: '数据结构、计算机组成原理' },
      { semester: '第3学期', name: '操作系统、数据库原理' },
      { semester: '第4学期', name: '计算机网络原理、TCP/IP协议' },
      { semester: '第5学期', name: '网络安全、路由交换技术' },
      { semester: '第6学期', name: '网络设计、网络管理' },
      { semester: '第7学期', name: '云计算、SDN技术' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于互联网企业、网络设备厂商、电信运营商、企业IT部门。',
    teachers: '专业教师具有网络工程实践经验。',
    salary: '毕业五年平均月薪约 6500-12000元'
  },
  {
    id: 'new-energy-science',
    name: '新能源科学与工程',
    college: '电气与信息工程学院',
    type: 'physics',
    minScore: 527,
    avgScore: 531,
    maxScore: 540,
    plan: 80,
    rank: 123540,
    tags: ['03专业组', '无限制', '新能源', '新兴工科'],
    hotLevel: 4,
    description: '培养掌握新能源科学与工程基本理论，能在太阳能、风能、储能、新能源发电等领域从事设计、研发、生产的高级工程技术人才。',
    features: ['新能源方向', '太阳能风能应用', '新能源产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '工程力学、线性代数' },
      { semester: '第3学期', name: '热力学、流体力学' },
      { semester: '第4学期', name: '传热学、工程材料' },
      { semester: '第5学期', name: '新能源技术、太阳能工程' },
      { semester: '第6学期', name: '风能工程、储能技术' },
      { semester: '第7学期', name: '专业实习、新能源发电系统' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于新能源企业、光伏企业、风电企业、储能企业、电力系统。',
    teachers: '专业教师具有新能源行业研究背景。',
    salary: '毕业五年平均月薪约 6500-12000元'
  },
  {
    id: 'intelligent-equipment',
    name: '智能装备与系统',
    college: '机械工程学院',
    type: 'physics',
    minScore: 525,
    avgScore: 529,
    maxScore: 538,
    plan: 70,
    rank: 126403,
    tags: ['03专业组', '无限制', '智能装备', '新兴工科'],
    hotLevel: 4,
    description: '培养掌握智能装备与系统基本理论和技术，能在智能装备设计、智能制造、工业机器人等领域从事设计、开发、应用的高级工程技术人才。',
    features: ['智能装备方向', '工业机器人应用', '智能制造系统'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、机械制图' },
      { semester: '第2学期', name: '理论力学、线性代数' },
      { semester: '第3学期', name: '材料力学、机械设计' },
      { semester: '第4学期', name: '电工电子技术、液压与气动' },
      { semester: '第5学期', name: '单片机原理、PLC技术' },
      { semester: '第6学期', name: '工业机器人、智能检测技术' },
      { semester: '第7学期', name: '专业实习、智能制造系统' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于智能制造企业、装备制造企业、工业机器人企业。',
    teachers: '专业教师具有智能装备研发经验。',
    salary: '毕业五年平均月薪约 6500-12000元'
  },
  {
    id: 'optoelectronic-science',
    name: '光电信息科学与工程',
    college: '电气与信息工程学院',
    type: 'physics',
    minScore: 525,
    avgScore: 529,
    maxScore: 538,
    plan: 70,
    rank: 126403,
    tags: ['03专业组', '无限制', '光电技术', '信息产业'],
    hotLevel: 4,
    description: '培养掌握光电信息科学与工程基本理论，能在光电技术、激光技术、光纤通信、显示技术等领域从事研发、生产的高级工程技术人才。',
    features: ['光电信息方向', '激光与光纤通信应用', '光电子产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '线性代数、电路分析' },
      { semester: '第3学期', name: '光学原理、模拟电子技术' },
      { semester: '第4学期', name: '激光原理、数字电子技术' },
      { semester: '第5学期', name: '光电检测技术、光纤通信' },
      { semester: '第6学期', name: '显示技术、光电子器件' },
      { semester: '第7学期', name: '专业实习、光电系统设计' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于光电企业、通信企业、显示技术企业、科研院所。',
    teachers: '专业教师具有光电技术研究背景。',
    salary: '毕业五年平均月薪约 6500-12000元'
  },
  {
    id: 'applied-statistics',
    name: '应用统计学',
    college: '计算机学院',
    type: 'physics',
    minScore: 525,
    avgScore: 529,
    maxScore: 538,
    plan: 60,
    rank: 126403,
    tags: ['03专业组', '无限制', '统计学', '数据分析'],
    hotLevel: 3,
    description: '培养掌握应用统计学基本理论和方法，能在数据分析、统计建模、大数据应用等领域从事数据处理、统计分析、决策支持的高级专门人才。',
    features: ['应用统计学方向', '数据分析应用', '大数据时代需求'],
    courses: [
      { semester: '第1学期', name: '高等数学、概率论、线性代数' },
      { semester: '第2学期', name: '数理统计、C语言程序设计' },
      { semester: '第3学期', name: '回归分析、R语言' },
      { semester: '第4学期', name: '抽样调查、多元统计分析' },
      { semester: '第5学期', name: '时间序列分析、数据挖掘' },
      { semester: '第6学期', name: '统计软件应用、机器学习基础' },
      { semester: '第7学期', name: '专业实习、数据分析项目' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于金融机构、数据公司、互联网企业、政府统计部门。',
    teachers: '专业教师具有统计学和数据分析背景。',
    salary: '毕业五年平均月薪约 6000-11000元'
  },
  {
    id: 'data-science',
    name: '数据科学与大数据技术',
    college: '计算机学院',
    type: 'physics',
    minScore: 525,
    avgScore: 529,
    maxScore: 538,
    plan: 80,
    rank: 126403,
    tags: ['03专业组', '有色觉要求', '大数据', '新兴专业'],
    hotLevel: 5,
    description: '培养掌握数据科学与大数据技术基本理论，能在大数据处理、数据分析、数据挖掘、云计算等领域从事研发、应用的高级工程技术人才。',
    features: ['大数据方向', '数据挖掘与分析应用', '新兴热门专业'],
    courses: [
      { semester: '第1学期', name: '高等数学、Python程序设计' },
      { semester: '第2学期', name: '线性代数、概率论与数理统计' },
      { semester: '第3学期', name: '数据结构、数据库原理' },
      { semester: '第4学期', name: '大数据基础、Hadoop技术' },
      { semester: '第5学期', name: '数据挖掘、机器学习' },
      { semester: '第6学期', name: 'Spark技术、数据可视化' },
      { semester: '第7学期', name: '深度学习、大数据项目实战' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于互联网企业、大数据企业、金融机构、科研院所。',
    teachers: '专业教师紧跟大数据技术发展。',
    salary: '毕业五年平均月薪约 7000-13000元'
  },

  // ========== 物理类 · 专业组02（中分段） ==========
  {
    id: 'financial-management',
    name: '财务管理',
    college: '经济管理学院',
    type: 'physics',
    minScore: 523,
    avgScore: 527,
    maxScore: 536,
    plan: 80,
    rank: 129306,
    tags: ['02专业组', '有色觉要求', '经管类'],
    hotLevel: 4,
    description: '培养掌握财务管理基本理论和方法，能在企事业单位、金融机构从事财务核算、资金管理、投资分析的高级专门人才。',
    features: ['财务管理方向', '金融投资应用', '企业财务管理'],
    courses: [
      { semester: '第1学期', name: '高等数学、管理学原理、基础会计' },
      { semester: '第2学期', name: '微观经济学、统计学' },
      { semester: '第3学期', name: '中级财务会计、财务管理' },
      { semester: '第4学期', name: '投资学、金融学' },
      { semester: '第5学期', name: '高级财务管理、成本管理' },
      { semester: '第6学期', name: '财务分析、税务筹划' },
      { semester: '第7学期', name: '专业实习、财务综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于各类企业、银行、证券公司、投资机构。',
    teachers: '专业教师具有丰富的财务管理实践经验。',
    salary: '毕业五年平均月薪约 6000-11000元'
  },
  {
    id: 'new-energy-vehicle',
    name: '新能源汽车工程',
    college: '机械工程学院',
    type: 'physics',
    minScore: 522,
    avgScore: 526,
    maxScore: 535,
    plan: 80,
    rank: 130716,
    tags: ['02专业组', '无限制', '新能源', '汽车产业'],
    hotLevel: 4,
    description: '培养掌握新能源汽车工程基本理论和技术，能在新能源汽车设计、电池电机、整车控制等领域从事研发、生产的高级工程技术人才。',
    features: ['新能源汽车方向', '三电系统应用', '新能源汽车产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、机械制图' },
      { semester: '第2学期', name: '理论力学、线性代数' },
      { semester: '第3学期', name: '材料力学、机械设计' },
      { semester: '第4学期', name: '电工电子技术、汽车构造' },
      { semester: '第5学期', name: '汽车理论、电池技术' },
      { semester: '第6学期', name: '电机驱动技术、整车控制' },
      { semester: '第7学期', name: '专业实习、新能源汽车综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于新能源汽车企业、电池企业、汽车零部件企业。',
    teachers: '专业教师具有新能源汽车行业背景。',
    salary: '毕业五年平均月薪约 6500-12000元'
  },
  {
    id: 'mechanical-design',
    name: '机械设计制造及其自动化',
    college: '机械工程学院',
    type: 'physics',
    minScore: 522,
    avgScore: 526,
    maxScore: 535,
    plan: 120,
    rank: 130716,
    tags: ['02专业组', '无限制', '机械类', '传统优势'],
    hotLevel: 4,
    description: '培养掌握机械设计制造基本理论和技术，能在机械制造、装备设计、生产管理等领域从事设计、制造、管理的高级工程技术人才。',
    features: ['机械设计制造方向', '装备制造应用', '传统优势专业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、机械制图' },
      { semester: '第2学期', name: '理论力学、线性代数' },
      { semester: '第3学期', name: '材料力学、机械原理' },
      { semester: '第4学期', name: '机械设计、工程材料' },
      { semester: '第5学期', name: '机械制造技术、数控技术' },
      { semester: '第6学期', name: '机电传动控制、CAD/CAM' },
      { semester: '第7学期', name: '专业实习、机械设计综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于机械制造企业、装备制造企业、汽车企业。',
    teachers: '师资力量雄厚，工程实践经验丰富。',
    salary: '毕业五年平均月薪约 6000-11000元'
  },
  {
    id: 'information-management',
    name: '信息管理与信息系统',
    college: '经济管理学院',
    type: 'physics',
    minScore: 520,
    avgScore: 524,
    maxScore: 533,
    plan: 70,
    rank: 133471,
    tags: ['02专业组', '有色觉要求', '信息管理', '经管+技术'],
    hotLevel: 3,
    description: '培养掌握信息管理与信息系统基本理论，能在企业信息化管理、信息系统设计、数据分析等领域从事管理与技术工作的高级专门人才。',
    features: ['信息管理方向', '企业信息化应用', '管理与技术结合'],
    courses: [
      { semester: '第1学期', name: '高等数学、管理学原理、基础会计' },
      { semester: '第2学期', name: '经济学、程序设计' },
      { semester: '第3学期', name: '数据结构、数据库原理' },
      { semester: '第4学期', name: '管理信息系统、企业管理' },
      { semester: '第5学期', name: '信息系统分析与设计、ERP' },
      { semester: '第6学期', name: '商务智能、信息安全' },
      { semester: '第7学期', name: '专业实习、信息系统项目' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于各类企业IT部门、信息咨询公司、ERP实施企业。',
    teachers: '专业教师兼具管理和信息技术背景。',
    salary: '毕业五年平均月薪约 6000-10000元'
  },
  {
    id: 'energy-power-engineering',
    name: '能源与动力工程',
    college: '机械工程学院',
    type: 'physics',
    minScore: 520,
    avgScore: 524,
    maxScore: 533,
    plan: 80,
    rank: 133471,
    tags: ['02专业组', '无限制', '能源动力', '传统工科'],
    hotLevel: 3,
    description: '培养掌握能源与动力工程基本理论，能在动力机械、能源转换、制冷与空调、新能源等领域从事设计、研发、生产的高级工程技术人才。',
    features: ['能源动力方向', '动力机械与热能应用', '能源产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '线性代数、工程制图' },
      { semester: '第3学期', name: '理论力学、材料力学' },
      { semester: '第4学期', name: '热力学、传热学' },
      { semester: '第5学期', name: '流体力学、动力机械原理' },
      { semester: '第6学期', name: '制冷技术、能源利用技术' },
      { semester: '第7学期', name: '专业实习、动力工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于电力企业、动力设备制造企业、新能源企业。',
    teachers: '专业教师具有能源动力行业背景。',
    salary: '毕业五年平均月薪约 6000-10000元'
  },
  {
    id: 'intelligent-manufacturing',
    name: '智能制造工程',
    college: '机械工程学院',
    type: 'physics',
    minScore: 520,
    avgScore: 524,
    maxScore: 533,
    plan: 80,
    rank: 133471,
    tags: ['02专业组', '无限制', '智能制造', '新兴工科'],
    hotLevel: 4,
    description: '培养掌握智能制造工程基本理论和技术，能在智能制造系统、工业互联网、数字化工厂等领域从事设计、开发的高级工程技术人才。',
    features: ['智能制造方向', '数字化工厂应用', '制造业升级'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、机械制图' },
      { semester: '第2学期', name: '理论力学、线性代数' },
      { semester: '第3学期', name: '材料力学、机械设计' },
      { semester: '第4学期', name: '电工电子技术、C语言' },
      { semester: '第5学期', name: '数控技术、PLC技术' },
      { semester: '第6学期', name: '工业机器人、MES系统' },
      { semester: '第7学期', name: '专业实习、智能制造系统' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于智能制造企业、汽车企业、电子制造企业。',
    teachers: '专业教师紧跟智能制造技术发展。',
    salary: '毕业五年平均月薪约 6000-11000元'
  },
  {
    id: 'mechanical-engineering',
    name: '机械工程',
    college: '机械工程学院',
    type: 'physics',
    minScore: 520,
    avgScore: 524,
    maxScore: 533,
    plan: 80,
    rank: 133471,
    tags: ['02专业组', '无限制', '机械类', '传统工科'],
    hotLevel: 3,
    description: '培养掌握机械工程基本理论和技术，能在机械设计、机械制造、机电一体化等领域从事设计、制造、管理的高级工程技术人才。',
    features: ['机械工程方向', '机械设计与制造应用', '传统工科专业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、机械制图' },
      { semester: '第2学期', name: '理论力学、线性代数' },
      { semester: '第3学期', name: '材料力学、机械原理' },
      { semester: '第4学期', name: '机械设计、工程材料' },
      { semester: '第5学期', name: '机械制造技术、数控技术' },
      { semester: '第6学期', name: '机电一体化、CAD/CAM' },
      { semester: '第7学期', name: '专业实习、机械工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于机械制造企业、装备制造企业、汽车企业。',
    teachers: '专业教师具有丰富的机械工程实践经验。',
    salary: '毕业五年平均月薪约 6000-10000元'
  },
  {
    id: 'new-energy-materials',
    name: '新能源材料与器件',
    college: '新能源与材料学院',
    type: 'physics',
    minScore: 519,
    avgScore: 523,
    maxScore: 532,
    plan: 70,
    rank: 134946,
    tags: ['02专业组', '无限制', '新材料', '新能源'],
    hotLevel: 4,
    description: '培养掌握新能源材料与器件基本理论，能在新能源电池、光伏材料、储能材料等领域从事研发、生产的高级工程技术人才。',
    features: ['新能源材料方向', '电池与光伏应用', '新材料新能源产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、物理化学' },
      { semester: '第3学期', name: '材料科学基础、固体物理' },
      { semester: '第4学期', name: '电化学原理、半导体物理' },
      { semester: '第5学期', name: '新能源材料、电池材料' },
      { semester: '第6学期', name: '光伏材料、储能材料' },
      { semester: '第7学期', name: '专业实习、新能源材料综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于新能源企业、电池企业、光伏企业、新材料企业。',
    teachers: '专业教师具有新能源材料研究背景。',
    salary: '毕业五年平均月薪约 6500-11000元'
  },
  {
    id: 'mechatronic-engineering',
    name: '机械电子工程',
    college: '机械工程学院',
    type: 'physics',
    minScore: 519,
    avgScore: 523,
    maxScore: 532,
    plan: 70,
    rank: 134946,
    tags: ['02专业组', '无限制', '机械电子', '机电一体化'],
    hotLevel: 3,
    description: '培养掌握机械电子工程基本理论和技术，能在机电一体化、智能装备、工业自动化等领域从事设计、开发的高级工程技术人才。',
    features: ['机械电子方向', '机电一体化应用', '智能装备设计'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、机械制图' },
      { semester: '第2学期', name: '理论力学、线性代数' },
      { semester: '第3学期', name: '材料力学、机械原理' },
      { semester: '第4学期', name: '电工电子技术、机械设计' },
      { semester: '第5学期', name: '单片机原理、PLC技术' },
      { semester: '第6学期', name: '液压与气动、机电传动控制' },
      { semester: '第7学期', name: '专业实习、机电一体化系统' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于机电企业、自动化企业、装备制造企业。',
    teachers: '专业教师具有机电工程实践经验。',
    salary: '毕业五年平均月薪约 6000-10000元'
  },
  {
    id: 'vehicle-engineering',
    name: '车辆工程',
    college: '机械工程学院',
    type: 'physics',
    minScore: 519,
    avgScore: 523,
    maxScore: 532,
    plan: 80,
    rank: 134946,
    tags: ['02专业组', '无限制', '汽车工程', '汽车产业'],
    hotLevel: 4,
    description: '培养掌握车辆工程基本理论和技术，能在汽车设计、汽车制造、汽车电子等领域从事研发、生产的高级工程技术人才。',
    features: ['车辆工程方向', '汽车设计与制造应用', '汽车产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、机械制图' },
      { semester: '第2学期', name: '理论力学、线性代数' },
      { semester: '第3学期', name: '材料力学、机械原理' },
      { semester: '第4学期', name: '机械设计、汽车构造' },
      { semester: '第5学期', name: '汽车理论、汽车设计' },
      { semester: '第6学期', name: '汽车制造工艺、汽车电子' },
      { semester: '第7学期', name: '专业实习、汽车工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于汽车制造企业、汽车零部件企业、汽车研发机构。',
    teachers: '专业教师具有汽车行业丰富经验。',
    salary: '毕业五年平均月薪约 6000-11000元'
  },
  {
    id: 'international-trade',
    name: '国际经济与贸易',
    college: '经济管理学院',
    type: 'physics',
    minScore: 518,
    avgScore: 522,
    maxScore: 531,
    plan: 70,
    rank: 136396,
    tags: ['02专业组', '无限制', '经管类', '外贸'],
    hotLevel: 3,
    description: '培养掌握国际经济与贸易基本理论和技能，能在涉外经济贸易部门、外资企业、进出口企业从事业务和管理工作的高级专门人才。',
    features: ['国际贸易方向', '外语能力强', '外向型经济'],
    courses: [
      { semester: '第1学期', name: '高等数学、英语、微观经济学' },
      { semester: '第2学期', name: '宏观经济学、国际贸易理论' },
      { semester: '第3学期', name: '统计学、国际贸易实务' },
      { semester: '第4学期', name: '金融学、国际金融' },
      { semester: '第5学期', name: '国际结算、外贸函电' },
      { semester: '第6学期', name: '国际商法、跨境电商' },
      { semester: '第7学期', name: '专业实习、外贸综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于外贸企业、外资企业、进出口公司、跨境电商企业。',
    teachers: '专业教师具有国际贸易实践经验。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'financial-engineering',
    name: '金融工程',
    college: '经济管理学院',
    type: 'physics',
    minScore: 517,
    avgScore: 521,
    maxScore: 530,
    plan: 70,
    rank: 137743,
    tags: ['02专业组', '无限制', '金融', '经管类'],
    hotLevel: 4,
    description: '培养掌握金融工程基本理论和方法，能在金融机构、证券公司、投资机构从事金融分析、产品设计、风险管理的高级专门人才。',
    features: ['金融工程方向', '金融建模与量化应用', '金融行业'],
    courses: [
      { semester: '第1学期', name: '高等数学、微积分、微观经济学' },
      { semester: '第2学期', name: '线性代数、概率论、宏观经济学' },
      { semester: '第3学期', name: '数理统计、金融学' },
      { semester: '第4学期', name: '计量经济学、投资学' },
      { semester: '第5学期', name: '金融工程、衍生金融工具' },
      { semester: '第6学期', name: '风险管理、固定收益证券' },
      { semester: '第7学期', name: '专业实习、金融建模实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于银行、证券公司、基金公司、投资机构。',
    teachers: '专业教师具有金融行业背景。',
    salary: '毕业五年平均月薪约 6500-12000元'
  },
  {
    id: 'traffic-engineering',
    name: '交通工程',
    college: '土木工程学院',
    type: 'physics',
    minScore: 517,
    avgScore: 521,
    maxScore: 530,
    plan: 70,
    rank: 137743,
    tags: ['02专业组', '无限制', '交通运输', '基础设施'],
    hotLevel: 3,
    description: '培养掌握交通工程基本理论和技术，能在道路交通、交通规划、交通管理等领域从事设计、规划、管理的高级工程技术人才。',
    features: ['交通工程方向', '交通规划与设计应用', '基础设施建设'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、工程制图' },
      { semester: '第2学期', name: '理论力学、线性代数' },
      { semester: '第3学期', name: '材料力学、工程测量' },
      { semester: '第4学期', name: '结构力学、道路建筑材料' },
      { semester: '第5学期', name: '交通工程学、交通规划' },
      { semester: '第6学期', name: '道路勘测设计、交通管理' },
      { semester: '第7学期', name: '专业实习、交通工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于交通规划设计院、公路建设企业、交通管理部门。',
    teachers: '专业教师具有交通工程实践经验。',
    salary: '毕业五年平均月薪约 6000-10000元'
  },
  {
    id: 'e-commerce',
    name: '电子商务',
    college: '经济管理学院',
    type: 'physics',
    minScore: 516,
    avgScore: 520,
    maxScore: 529,
    plan: 70,
    rank: 139204,
    tags: ['02专业组', '无限制', '电商', '互联网+'],
    hotLevel: 4,
    description: '培养掌握电子商务基本理论和技能，能在电商企业、互联网企业、传统企业电商部门从事运营、营销、技术工作的高级专门人才。',
    features: ['电子商务方向', '网络营销应用', '互联网+时代热门'],
    courses: [
      { semester: '第1学期', name: '高等数学、管理学原理、基础会计' },
      { semester: '第2学期', name: '电子商务概论、市场营销' },
      { semester: '第3学期', name: '网络营销、网页设计' },
      { semester: '第4学期', name: '电子商务运营、电商平台技术' },
      { semester: '第5学期', name: '跨境电商、电子商务数据分析' },
      { semester: '第6学期', name: '电商文案、电商法律' },
      { semester: '第7学期', name: '专业实习、电商项目实战' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于电子商务企业、互联网公司、跨境电商企业、传统企业电商部门。',
    teachers: '专业教师紧跟电子商务行业发展。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'business-administration',
    name: '工商管理',
    college: '经济管理学院',
    type: 'physics',
    minScore: 516,
    avgScore: 520,
    maxScore: 529,
    plan: 80,
    rank: 139204,
    tags: ['02专业组', '有色觉要求', '经管类', '企业管理'],
    hotLevel: 3,
    description: '培养掌握工商管理基本理论和方法，能在各类企业、事业单位从事经营管理、市场营销、人力资源管理等工作的高级专门人才。',
    features: ['企业管理方向', '综合管理技能', '广泛就业面'],
    courses: [
      { semester: '第1学期', name: '高等数学、管理学原理、基础会计' },
      { semester: '第2学期', name: '微观经济学、统计学' },
      { semester: '第3学期', name: '市场营销、财务管理' },
      { semester: '第4学期', name: '组织行为学、人力资源管理' },
      { semester: '第5学期', name: '运营管理、战略管理' },
      { semester: '第6学期', name: '企业管理案例、商务谈判' },
      { semester: '第7学期', name: '专业实习、企业管理综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于各类企业、管理咨询公司、事业单位。',
    teachers: '专业教师具有企业管理实践经验。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'fashion-design',
    name: '服装设计与工程',
    college: '纺织服装学院',
    type: 'physics',
    minScore: 515,
    avgScore: 519,
    maxScore: 528,
    plan: 60,
    rank: 140609,
    tags: ['02专业组', '无限制', '服装设计', '纺织服装'],
    hotLevel: 3,
    description: '培养掌握服装设计与工程基本理论和技术，能在服装企业从事服装设计、服装工艺、生产管理、市场营销的高级专门人才。',
    features: ['服装设计与工程方向', '服装工艺与设计应用', '纺织服装产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、服装素描' },
      { semester: '第2学期', name: '服装色彩、服装材料学' },
      { semester: '第3学期', name: '服装结构设计、服装工艺' },
      { semester: '第4学期', name: '服装设计、服装CAD' },
      { semester: '第5学期', name: '服装工业制版、服装营销' },
      { semester: '第6学期', name: '服装品牌策划、服装陈列' },
      { semester: '第7学期', name: '专业实习、服装设计综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于服装企业、纺织企业、服装贸易公司。',
    teachers: '专业教师具有服装设计行业经验。',
    salary: '毕业五年平均月薪约 5000-9000元'
  },
  {
    id: 'polymer-materials',
    name: '高分子材料与工程',
    college: '新能源与材料学院',
    type: 'physics',
    minScore: 514,
    avgScore: 518,
    maxScore: 527,
    plan: 70,
    rank: 142069,
    tags: ['02专业组', '有色觉要求', '材料类', '工科'],
    hotLevel: 3,
    description: '培养掌握高分子材料与工程基本理论，能在高分子材料研发、塑料橡胶、复合材料等领域从事生产、研发的高级工程技术人才。',
    features: ['高分子材料方向', '塑料橡胶材料应用', '材料产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、分析化学' },
      { semester: '第4学期', name: '高分子化学、高分子物理' },
      { semester: '第5学期', name: '高分子材料成型工艺' },
      { semester: '第6学期', name: '聚合物加工原理、复合材料' },
      { semester: '第7学期', name: '专业实习、高分子材料综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于塑料企业、橡胶企业、新材料企业、汽车材料企业。',
    teachers: '专业教师具有高分子材料研究背景。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'pharmaceutical-engineering',
    name: '制药工程',
    college: '医药化工学院',
    type: 'physics',
    minScore: 513,
    avgScore: 517,
    maxScore: 526,
    plan: 70,
    rank: 143441,
    tags: ['02专业组', '有色觉要求', '医药', '化工'],
    hotLevel: 4,
    description: '培养掌握制药工程基本理论和技术，能在制药企业从事药品研发、生产、质量控制、管理工作的高级工程技术人才。',
    features: ['制药工程方向', '药品研发与生产应用', '医药健康产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、分析化学' },
      { semester: '第4学期', name: '生物化学、药物化学' },
      { semester: '第5学期', name: '药物分析、药理学' },
      { semester: '第6学期', name: '制药工艺学、药剂学' },
      { semester: '第7学期', name: '专业实习、制药工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于制药企业、医药研发机构、药品监管部门。',
    teachers: '专业教师具有制药行业丰富经验。',
    salary: '毕业五年平均月薪约 6000-11000元'
  },
  {
    id: 'process-equipment',
    name: '过程装备与控制工程',
    college: '医药化工学院',
    type: 'physics',
    minScore: 513,
    avgScore: 517,
    maxScore: 526,
    plan: 70,
    rank: 143441,
    tags: ['02专业组', '有色觉要求', '化工装备', '过程控制'],
    hotLevel: 3,
    description: '培养掌握过程装备与控制工程基本理论，能在化工装备、过程控制、压力容器等领域从事设计、生产、管理的高级工程技术人才。',
    features: ['过程装备方向', '化工设备设计应用', '过程控制技术'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '工程制图、理论力学' },
      { semester: '第3学期', name: '材料力学、机械设计' },
      { semester: '第4学期', name: '热力学、过程原理' },
      { semester: '第5学期', name: '过程装备设计、压力容器设计' },
      { semester: '第6学期', name: '过程控制、化工仪表' },
      { semester: '第7学期', name: '专业实习、过程装备综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于化工企业、石化企业、装备制造企业。',
    teachers: '专业教师具有化工装备实践经验。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },

  // ========== 物理类 · 512分档（同分专业） ==========
  {
    id: 'food-quality-safety',
    name: '食品质量与安全',
    college: '食品科学与工程学院',
    type: 'physics',
    minScore: 512,
    avgScore: 516,
    maxScore: 525,
    plan: 70,
    rank: 144773,
    tags: ['同分专业', '食品', '质量安全', '大健康'],
    hotLevel: 3,
    description: '培养掌握食品质量与安全基本理论和技术，能在食品企业、食品检测机构从事食品质量检测、食品安全管理的高级专门人才。',
    features: ['食品质量与安全方向', '食品检测技术应用', '食品安全管理'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '有机化学、分析化学' },
      { semester: '第3学期', name: '生物化学、食品化学' },
      { semester: '第4学期', name: '食品微生物学、食品营养学' },
      { semester: '第5学期', name: '食品分析、食品安全学' },
      { semester: '第6学期', name: '食品质量管理、食品标准与法规' },
      { semester: '第7学期', name: '专业实习、食品检测综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于食品企业、食品检测机构、食品药品监管部门。',
    teachers: '专业教师具有食品行业经验。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },
  {
    id: 'chemical-engineering',
    name: '化学工程与工艺',
    college: '医药化工学院',
    type: 'physics',
    minScore: 512,
    avgScore: 516,
    maxScore: 525,
    plan: 80,
    rank: 144773,
    tags: ['同分专业', '化工', '传统工科'],
    hotLevel: 3,
    description: '培养掌握化学工程与工艺基本理论和技术，能在化工企业、石化企业从事化工生产、研发、管理的高级工程技术人才。',
    features: ['化学工程方向', '化工工艺与生产应用', '化工产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、分析化学' },
      { semester: '第4学期', name: '化工原理、化工热力学' },
      { semester: '第5学期', name: '化学反应工程、化工工艺学' },
      { semester: '第6学期', name: '化工设计、分离工程' },
      { semester: '第7学期', name: '专业实习、化工工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于化工企业、石化企业、医药企业、科研院所。',
    teachers: '专业教师具有化工研究背景。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'engineering-management',
    name: '工程管理',
    college: '经济管理学院',
    type: 'physics',
    minScore: 512,
    avgScore: 516,
    maxScore: 525,
    plan: 70,
    rank: 144773,
    tags: ['同分专业', '工程管理', '建筑管理'],
    hotLevel: 3,
    description: '培养掌握工程管理基本理论和方法，能在建筑企业、工程项目管理公司从事工程项目管理、造价咨询、招投标的高级专门人才。',
    features: ['工程管理方向', '工程项目管理应用', '建筑+管理'],
    courses: [
      { semester: '第1学期', name: '高等数学、管理学原理、工程制图' },
      { semester: '第2学期', name: '工程力学、经济学' },
      { semester: '第3学期', name: '工程结构、建筑材料' },
      { semester: '第4学期', name: '工程项目管理、工程经济学' },
      { semester: '第5学期', name: '工程估价、工程造价' },
      { semester: '第6学期', name: '工程招投标与合同管理' },
      { semester: '第7学期', name: '专业实习、工程管理综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于建筑企业、房地产公司、工程咨询公司。',
    teachers: '专业教师兼具工程和管理背景。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'english-physics',
    name: '英语',
    college: '外国语学院',
    type: 'physics',
    minScore: 512,
    avgScore: 516,
    maxScore: 525,
    plan: 60,
    rank: 144773,
    tags: ['同分专业', '外语', '英语'],
    hotLevel: 3,
    description: '培养掌握英语语言文学基本理论和技能，能在教育、翻译、外贸、外企等领域从事英语教学、翻译、涉外工作的高级专门人才。',
    features: ['英语专业方向', '翻译与教学应用', '跨文化交流能力'],
    courses: [
      { semester: '第1学期', name: '基础英语、英语听力、英语口语' },
      { semester: '第2学期', name: '英语阅读、英语写作' },
      { semester: '第3学期', name: '高级英语、英语语法' },
      { semester: '第4学期', name: '英国文学、美国文学' },
      { semester: '第5学期', name: '翻译理论与实践、英语语言学' },
      { semester: '第6学期', name: '口译、英语教学法' },
      { semester: '第7学期', name: '专业实习、英语综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于中小学、培训机构、翻译公司、外贸企业、外资企业。',
    teachers: '专业教师具有海外留学和教学经验。',
    salary: '毕业五年平均月薪约 5000-9000元'
  },
  {
    id: 'emergency-management',
    name: '应急管理',
    college: '环境科学与工程学院',
    type: 'physics',
    minScore: 512,
    avgScore: 516,
    maxScore: 525,
    plan: 60,
    rank: 144773,
    tags: ['同分专业', '应急管理', '安全生产'],
    hotLevel: 3,
    description: '培养掌握应急管理基本理论和方法，能在安全生产监督管理、应急救援、灾害防治等领域从事管理和技术工作的高级专门人才。',
    features: ['应急管理方向', '安全生产管理应用', '应急救援'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '管理学原理、应急管理概论' },
      { semester: '第3学期', name: '安全科学原理、灾害学' },
      { semester: '第4学期', name: '应急救援技术、事故预防' },
      { semester: '第5学期', name: '安全生产管理、应急指挥' },
      { semester: '第6学期', name: '风险评估、应急预案编制' },
      { semester: '第7学期', name: '专业实习、应急管理综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于政府应急管理部门、安全生产监管部门、企业安全管理部门。',
    teachers: '专业教师具有应急管理实践经验。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },
  {
    id: 'applied-chemistry',
    name: '应用化学',
    college: '新能源与材料学院',
    type: 'physics',
    minScore: 512,
    avgScore: 516,
    maxScore: 525,
    plan: 70,
    rank: 144773,
    tags: ['同分专业', '化学', '应用理科'],
    hotLevel: 3,
    description: '培养掌握应用化学基本理论和实验技能，能在化学化工、新材料、精细化工等领域从事研发、生产、质量分析的高级专门人才。',
    features: ['应用化学方向', '精细化工与分析应用', '化学与材料产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、分析化学' },
      { semester: '第4学期', name: '仪器分析、有机合成' },
      { semester: '第5学期', name: '精细化工、高分子化学' },
      { semester: '第6学期', name: '工业分析、环境化学' },
      { semester: '第7学期', name: '专业实习、应用化学综合实验' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于化工企业、新材料企业、检测机构、研发机构。',
    teachers: '专业教师具有化学研究和行业经验。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'architecture',
    name: '建筑学',
    college: '土木工程学院',
    type: 'physics',
    minScore: 512,
    avgScore: 516,
    maxScore: 525,
    plan: 70,
    rank: 144773,
    tags: ['同分专业', '建筑设计'],
    hotLevel: 4,
    description: '培养掌握建筑学基本理论和技能，能在建筑设计、城市规划、景观设计等领域从事设计、管理工作的高级专门人才。',
    features: ['建筑设计方向', '城市规划应用', '创意设计'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、建筑制图' },
      { semester: '第2学期', name: '建筑设计基础、建筑概论' },
      { semester: '第3学期', name: '建筑史、建筑力学' },
      { semester: '第4学期', name: '建筑设计、建筑构造' },
      { semester: '第5学期', name: '城市规划原理、建筑物理' },
      { semester: '第6学期', name: '建筑设计、景观设计' },
      { semester: '第7学期', name: '专业实习、建筑设计综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于建筑设计院、规划设计院、房地产公司、建筑企业。',
    teachers: '专业教师具有建筑设计行业丰富经验。',
    salary: '毕业五年平均月薪约 6000-10000元'
  },
  {
    id: 'tourism-management-physics',
    name: '旅游管理',
    college: '经济管理学院',
    type: 'physics',
    minScore: 512,
    avgScore: 516,
    maxScore: 525,
    plan: 60,
    rank: 144773,
    tags: ['同分专业', '旅游', '服务管理'],
    hotLevel: 3,
    description: '培养掌握旅游管理基本理论和技能，能在旅游企业、酒店、景区从事旅游策划、酒店管理、景区管理的高级专门人才。',
    features: ['旅游管理方向', '旅游与酒店服务应用', '旅游产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、管理学原理、旅游学概论' },
      { semester: '第2学期', name: '经济学、旅游心理学' },
      { semester: '第3学期', name: '旅游市场营销、旅游经济学' },
      { semester: '第4学期', name: '酒店管理、旅游管理信息系统' },
      { semester: '第5学期', name: '旅游规划与开发、旅行社管理' },
      { semester: '第6学期', name: '景区管理、旅游英语' },
      { semester: '第7学期', name: '专业实习、旅游综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于旅游企业、酒店、旅行社、景区管理部门。',
    teachers: '专业教师具有旅游管理行业经验。',
    salary: '毕业五年平均月薪约 5000-9000元'
  },
  {
    id: 'japanese-physics',
    name: '日语',
    college: '外国语学院',
    type: 'physics',
    minScore: 512,
    avgScore: 516,
    maxScore: 525,
    plan: 60,
    rank: 144773,
    tags: ['同分专业', '外语', '日语'],
    hotLevel: 3,
    description: '培养掌握日语语言文学基本理论和技能，能在外企、外贸企业、教育机构从事日语翻译、教学、外贸业务的高级专门人才。',
    features: ['日语专业方向', '翻译与教学应用', '中日文化交流'],
    courses: [
      { semester: '第1学期', name: '基础日语、日语听力、日语口语' },
      { semester: '第2学期', name: '日语阅读、日语写作' },
      { semester: '第3学期', name: '高级日语、日语语法' },
      { semester: '第4学期', name: '日本文学、日本文化' },
      { semester: '第5学期', name: '翻译理论与实践、日语语言学' },
      { semester: '第6学期', name: '口译、日语教学法' },
      { semester: '第7学期', name: '专业实习、日语综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于日资企业、外贸企业、翻译公司、教育机构。',
    teachers: '专业教师具有日本留学和教学经验。',
    salary: '毕业五年平均月薪约 5000-9000元'
  },
  {
    id: 'food-science',
    name: '食品科学与工程',
    college: '食品科学与工程学院',
    type: 'physics',
    minScore: 511,
    avgScore: 515,
    maxScore: 524,
    plan: 70,
    rank: 146161,
    tags: ['有色觉要求', '食品', '工科'],
    hotLevel: 3,
    description: '培养掌握食品科学与工程基本理论和技术，能在食品企业从事食品研发、生产管理、质量控制的高级工程技术人才。',
    features: ['食品科学方向', '食品研发与生产应用', '食品产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '有机化学、分析化学' },
      { semester: '第3学期', name: '生物化学、食品化学' },
      { semester: '第4学期', name: '食品微生物学、食品营养学' },
      { semester: '第5学期', name: '食品工艺学、食品工程原理' },
      { semester: '第6学期', name: '食品工厂设计、食品机械设备' },
      { semester: '第7学期', name: '专业实习、食品工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于食品企业、食品研发机构、食品监管部门。',
    teachers: '专业教师具有食品行业经验。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },
  {
    id: 'materials-science',
    name: '材料科学与工程',
    college: '新能源与材料学院',
    type: 'physics',
    minScore: 509,
    avgScore: 513,
    maxScore: 522,
    plan: 80,
    rank: 148937,
    tags: ['无限制', '材料类', '传统工科'],
    hotLevel: 3,
    description: '培养掌握材料科学与工程基本理论和技术，能在材料研发、材料生产、新材料应用等领域从事研发、生产的高级工程技术人才。',
    features: ['材料科学方向', '材料研发与生产应用', '材料产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、材料科学基础' },
      { semester: '第4学期', name: '材料力学、材料物理性能' },
      { semester: '第5学期', name: '材料研究方法、金属材料学' },
      { semester: '第6学期', name: '材料加工原理、无机非金属材料' },
      { semester: '第7学期', name: '专业实习、材料工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于新材料企业、冶金企业、汽车材料企业、科研院所。',
    teachers: '专业教师具有材料科学研究背景。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'intelligent-construction',
    name: '智能建造',
    college: '土木工程学院',
    type: 'physics',
    minScore: 509,
    avgScore: 513,
    maxScore: 522,
    plan: 70,
    rank: 148937,
    tags: ['无限制', '智能建造', '新兴工科'],
    hotLevel: 3,
    description: '培养掌握智能建造基本理论和技术，能在建筑企业、工程项目中从事智能建造、BIM应用、工程管理的高级工程技术人才。',
    features: ['智能建造方向', 'BIM与智能施工应用', '建筑智能化'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、工程制图' },
      { semester: '第2学期', name: '理论力学、线性代数' },
      { semester: '第3学期', name: '材料力学、土木工程概论' },
      { semester: '第4学期', name: '结构力学、建筑材料' },
      { semester: '第5学期', name: 'BIM技术、混凝土结构' },
      { semester: '第6学期', name: '智能施工技术、工程项目管理' },
      { semester: '第7学期', name: '专业实习、智能建造综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于建筑企业、房地产公司、BIM咨询公司。',
    teachers: '专业教师紧跟智能建造技术发展。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'energy-chemistry',
    name: '能源化学',
    college: '新能源与材料学院',
    type: 'physics',
    minScore: 508,
    avgScore: 512,
    maxScore: 521,
    plan: 60,
    rank: 150365,
    tags: ['有色觉要求', '能源化学', '新能源'],
    hotLevel: 3,
    description: '培养掌握能源化学基本理论和技术，能在能源化学、新能源、电池材料、储能材料等领域从事研发、生产的高级专门人才。',
    features: ['能源化学方向', '能源与化学应用', '新能源产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、分析化学' },
      { semester: '第4学期', name: '能源化学、电化学原理' },
      { semester: '第5学期', name: '电池材料、储能材料' },
      { semester: '第6学期', name: '新能源技术、催化原理' },
      { semester: '第7学期', name: '专业实习、能源化学综合实验' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于新能源企业、电池企业、新材料企业、化工企业。',
    teachers: '专业教师具有能源化学研究背景。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'light-industry',
    name: '轻工工程',
    college: '医药化工学院',
    type: 'physics',
    minScore: 508,
    avgScore: 512,
    maxScore: 521,
    plan: 60,
    rank: 150365,
    tags: ['有色觉要求', '轻工', '传统工科'],
    hotLevel: 3,
    description: '培养掌握轻工工程基本理论和技术，能在轻工企业、日用化学品、造纸、皮革、食品等领域从事生产、研发的高级工程技术人才。',
    features: ['轻工工程方向', '轻工生产技术应用', '轻工产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、化工原理' },
      { semester: '第4学期', name: '轻工化学、微生物学' },
      { semester: '第5学期', name: '轻工工艺学、制浆造纸' },
      { semester: '第6学期', name: '皮革工程、日用化学品' },
      { semester: '第7学期', name: '专业实习、轻工工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于轻工企业、日化企业、造纸企业、皮革企业。',
    teachers: '专业教师具有轻工行业经验。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },
  {
    id: 'materials-physics',
    name: '材料物理',
    college: '新能源与材料学院',
    type: 'physics',
    minScore: 507,
    avgScore: 511,
    maxScore: 520,
    plan: 60,
    rank: 151738,
    tags: ['有色觉要求', '材料物理', '应用理科'],
    hotLevel: 3,
    description: '培养掌握材料物理基本理论和实验技能，能在新材料研发、材料性能测试、半导体材料等领域从事研发、生产的高级专门人才。',
    features: ['材料物理方向', '材料性能测试应用', '材料科学基础研究'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '线性代数、无机化学' },
      { semester: '第3学期', name: '固体物理、物理化学' },
      { semester: '第4学期', name: '材料力学、量子力学' },
      { semester: '第5学期', name: '材料物理性能、半导体物理' },
      { semester: '第6学期', name: '材料研究方法、功能材料' },
      { semester: '第7学期', name: '专业实习、材料物理综合实验' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于新材料企业、半导体企业、科研院所、检测机构。',
    teachers: '专业教师具有材料物理研究背景。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'metal-materials',
    name: '金属材料工程',
    college: '新能源与材料学院',
    type: 'physics',
    minScore: 507,
    avgScore: 511,
    maxScore: 520,
    plan: 70,
    rank: 151738,
    tags: ['无限制', '金属材料', '传统工科'],
    hotLevel: 3,
    description: '培养掌握金属材料工程基本理论和技术，能在冶金企业、金属材料企业从事金属材料研发、生产、加工的高级工程技术人才。',
    features: ['金属材料方向', '金属材料加工应用', '冶金产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、材料力学' },
      { semester: '第4学期', name: '材料科学基础、金属学' },
      { semester: '第5学期', name: '金属材料学、热处理原理' },
      { semester: '第6学期', name: '金属材料加工工艺、铸造工艺' },
      { semester: '第7学期', name: '专业实习、金属材料工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于冶金企业、金属材料企业、汽车企业、机械企业。',
    teachers: '专业教师具有金属材料行业经验。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'emergency-technology',
    name: '应急技术与管理',
    college: '环境科学与工程学院',
    type: 'physics',
    minScore: 507,
    avgScore: 511,
    maxScore: 520,
    plan: 60,
    rank: 151738,
    tags: ['无限制', '应急技术', '安全管理'],
    hotLevel: 3,
    description: '培养掌握应急技术与管理基本理论和技术，能在应急管理部门、企业安全生产部门从事应急技术、安全管理、应急救援的高级专门人才。',
    features: ['应急技术方向', '应急救援技术应用', '安全应急管理'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '管理学原理、应急管理概论' },
      { semester: '第3学期', name: '安全科学原理、灾害学' },
      { semester: '第4学期', name: '应急技术、事故预防' },
      { semester: '第5学期', name: '应急指挥、风险评估' },
      { semester: '第6学期', name: '应急预案编制、应急演练' },
      { semester: '第7学期', name: '专业实习、应急技术综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于应急管理部门、安全生产监管部门、企业安全部门。',
    teachers: '专业教师具有应急管理实践经验。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },
  {
    id: 'underground-space',
    name: '城市地下空间工程',
    college: '土木工程学院',
    type: 'physics',
    minScore: 507,
    avgScore: 511,
    maxScore: 520,
    plan: 70,
    rank: 151738,
    tags: ['无限制', '地下空间', '土木工程'],
    hotLevel: 3,
    description: '培养掌握城市地下空间工程基本理论和技术，能在地铁、隧道、地下管廊等工程领域从事设计、施工、管理的高级工程技术人才。',
    features: ['地下空间方向', '地铁隧道工程应用', '城市基础设施'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、工程制图' },
      { semester: '第2学期', name: '理论力学、线性代数' },
      { semester: '第3学期', name: '材料力学、土木工程概论' },
      { semester: '第4学期', name: '结构力学、土力学与地基' },
      { semester: '第5学期', name: '地下工程、岩石力学' },
      { semester: '第6学期', name: '地铁工程、隧道工程' },
      { semester: '第7学期', name: '专业实习、地下空间工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于地铁建设企业、隧道建设企业、市政工程企业。',
    teachers: '专业教师具有地下空间工程实践经验。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'environmental-equipment',
    name: '环保设备工程',
    college: '环境科学与工程学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 60,
    rank: 153113,
    tags: ['无限制', '环保设备', '环境工程'],
    hotLevel: 3,
    description: '培养掌握环保设备工程基本理论和技术，能在环保设备企业、环境工程公司从事环保设备设计、研发、生产的高级工程技术人才。',
    features: ['环保设备方向', '环保设备设计应用', '环保产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '工程制图、理论力学' },
      { semester: '第3学期', name: '材料力学、机械设计' },
      { semester: '第4学期', name: '环境工程原理、环境化学' },
      { semester: '第5学期', name: '环保设备设计、水处理设备' },
      { semester: '第6学期', name: '废气处理设备、固废处理设备' },
      { semester: '第7学期', name: '专业实习、环保设备工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于环保设备企业、环境工程公司、环境监测机构。',
    teachers: '专业教师具有环保行业经验。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },
  {
    id: 'aquatic-animal-medicine',
    name: '水生动物医学',
    college: '海洋技术学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 60,
    rank: 153113,
    tags: ['无限制', '水生动物', '兽医'],
    hotLevel: 3,
    description: '培养掌握水生动物医学基本理论和技术，能在水产养殖企业、渔业部门从事水生动物疾病防治、水产养殖管理的高级专门人才。',
    features: ['水生动物医学方向', '水产疾病防治应用', '水产养殖产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '有机化学、生物学' },
      { semester: '第3学期', name: '生物化学、微生物学' },
      { semester: '第4学期', name: '水生生物学、鱼类学' },
      { semester: '第5学期', name: '水产动物疾病学、水产药物学' },
      { semester: '第6学期', name: '水产养殖学、免疫学' },
      { semester: '第7学期', name: '专业实习、水生动物医学综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于水产养殖企业、渔业部门、水产科研机构。',
    teachers: '专业教师具有水产行业经验。',
    salary: '毕业五年平均月薪约 5000-9000元'
  },
  {
    id: 'materials-chemistry',
    name: '材料化学',
    college: '新能源与材料学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 60,
    rank: 153113,
    tags: ['多有色觉限制', '材料化学', '应用理科'],
    hotLevel: 3,
    description: '培养掌握材料化学基本理论和实验技能，能在新材料研发、化学材料、高分子材料等领域从事研发、生产的高级专门人才。',
    features: ['材料化学方向', '化学材料研发应用', '新材料产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、分析化学' },
      { semester: '第4学期', name: '材料化学、高分子化学' },
      { semester: '第5学期', name: '材料合成、高分子物理' },
      { semester: '第6学期', name: '功能材料、材料表征' },
      { semester: '第7学期', name: '专业实习、材料化学综合实验' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于新材料企业、化工企业、科研院所、检测机构。',
    teachers: '专业教师具有材料化学研究背景。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'marine-technology',
    name: '海洋技术',
    college: '海洋技术学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 60,
    rank: 153113,
    tags: ['多有色觉限制', '海洋技术', '海洋科学'],
    hotLevel: 3,
    description: '培养掌握海洋技术基本理论和技术，能在海洋观测、海洋调查、海洋资源开发、海洋工程等领域从事研发、应用的高级专门人才。',
    features: ['海洋技术方向', '海洋观测与调查应用', '海洋资源开发'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '海洋科学导论、线性代数' },
      { semester: '第3学期', name: '海洋物理学、海洋化学' },
      { semester: '第4学期', name: '海洋生物学、海洋地质学' },
      { semester: '第5学期', name: '海洋观测技术、海洋调查方法' },
      { semester: '第6学期', name: '海洋遥感、海洋数据处理' },
      { semester: '第7学期', name: '专业实习、海洋技术综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于海洋科研机构、海洋局、海洋技术企业。',
    teachers: '专业教师具有海洋科学研究背景。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },
  {
    id: 'marine-science',
    name: '海洋科学',
    college: '海洋技术学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 60,
    rank: 153113,
    tags: ['多有色觉限制', '海洋科学', '基础科学'],
    hotLevel: 3,
    description: '培养掌握海洋科学基本理论和技术，能在海洋科学研究、海洋资源调查、海洋环境保护等领域从事研究、应用的高级专门人才。',
    features: ['海洋科学方向', '海洋科学研究应用', '海洋资源与环境'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '海洋科学导论、线性代数' },
      { semester: '第3学期', name: '海洋物理学、海洋化学' },
      { semester: '第4学期', name: '海洋生物学、海洋地质学' },
      { semester: '第5学期', name: '物理海洋学、海洋环境学' },
      { semester: '第6学期', name: '海洋生态学、海洋资源学' },
      { semester: '第7学期', name: '专业实习、海洋科学综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于海洋科研机构、海洋局、海洋环保企业。',
    teachers: '专业教师具有海洋科学研究背景。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },
  {
    id: 'chemical-safety',
    name: '化工安全工程',
    college: '医药化工学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 60,
    rank: 153113,
    tags: ['多有色觉限制', '化工安全', '安全工程'],
    hotLevel: 3,
    description: '培养掌握化工安全工程基本理论和技术，能在化工企业、石化企业从事化工安全管理、安全评估、事故预防的高级工程技术人才。',
    features: ['化工安全方向', '化工安全评估应用', '化工安全生产'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、工程力学' },
      { semester: '第4学期', name: '化工原理、安全科学原理' },
      { semester: '第5学期', name: '化工安全工程、风险评估' },
      { semester: '第6学期', name: '事故预防与应急、化工工艺安全' },
      { semester: '第7学期', name: '专业实习、化工安全工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于化工企业、石化企业、安全生产监管部门。',
    teachers: '专业教师具有化工安全实践经验。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },
  {
    id: 'civil-engineering',
    name: '土木工程',
    college: '土木工程学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 100,
    rank: 153113,
    tags: ['多有色觉限制', '土木工程', '传统工科'],
    hotLevel: 4,
    description: '培养掌握土木工程基本理论和技术，能在建筑企业、公路建设、桥梁工程等领域从事设计、施工、管理的高级工程技术人才。',
    features: ['土木工程方向', '建筑施工与设计应用', '基础设施建设'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、工程制图' },
      { semester: '第2学期', name: '理论力学、线性代数' },
      { semester: '第3学期', name: '材料力学、土木工程概论' },
      { semester: '第4学期', name: '结构力学、建筑材料' },
      { semester: '第5学期', name: '土力学、混凝土结构' },
      { semester: '第6学期', name: '钢结构、桥梁工程' },
      { semester: '第7学期', name: '专业实习、土木工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于建筑企业、公路建设企业、桥梁工程企业、房地产公司。',
    teachers: '专业教师具有土木工程实践经验。',
    salary: '毕业五年平均月薪约 6000-11000元'
  },
  {
    id: 'environmental-engineering',
    name: '环境工程',
    college: '环境科学与工程学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 70,
    rank: 153113,
    tags: ['多有色觉限制', '环境工程', '环保'],
    hotLevel: 4,
    description: '培养掌握环境工程基本理论和技术，能在环保企业、污水处理、废气治理等领域从事设计、研发、运行的高级工程技术人才。',
    features: ['环境工程方向', '三废处理应用', '环保产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、分析化学' },
      { semester: '第4学期', name: '环境化学、环境微生物学' },
      { semester: '第5学期', name: '水污染控制工程、大气污染控制' },
      { semester: '第6学期', name: '固体废物处理、环境影响评价' },
      { semester: '第7学期', name: '专业实习、环境工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于环保企业、污水处理厂、环境监测机构、环保部门。',
    teachers: '专业教师具有环境工程研究背景。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'environmental-science',
    name: '环境科学',
    college: '环境科学与工程学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 70,
    rank: 153113,
    tags: ['多有色觉限制', '环境科学', '应用理科'],
    hotLevel: 3,
    description: '培养掌握环境科学基本理论和技术，能在环境监测、环境评价、环境管理等领域从事科研、管理的高级专门人才。',
    features: ['环境科学方向', '环境监测与评价应用', '环境管理'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、分析化学' },
      { semester: '第4学期', name: '环境化学、环境生物学' },
      { semester: '第5学期', name: '环境监测、环境质量评价' },
      { semester: '第6学期', name: '环境规划与管理、环境经济学' },
      { semester: '第7学期', name: '专业实习、环境科学综合实验' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于环境监测机构、环保部门、环境评价公司。',
    teachers: '专业教师具有环境科学研究背景。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },
  {
    id: 'bioengineering',
    name: '生物工程',
    college: '医药化工学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 70,
    rank: 153113,
    tags: ['多有色觉限制', '生物工程', '生物技术'],
    hotLevel: 3,
    description: '培养掌握生物工程基本理论和技术，能在生物制药、发酵工业、食品生物技术等领域从事研发、生产的高级工程技术人才。',
    features: ['生物工程方向', '生物技术应用', '生物医药产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '无机化学、有机化学' },
      { semester: '第3学期', name: '物理化学、生物化学' },
      { semester: '第4学期', name: '微生物学、分子生物学' },
      { semester: '第5学期', name: '发酵工程、生物分离工程' },
      { semester: '第6学期', name: '基因工程、酶工程' },
      { semester: '第7学期', name: '专业实习、生物工程综合实验' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于生物制药企业、食品企业、化工企业、科研院所。',
    teachers: '专业教师具有生物技术研究背景。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'applied-physics',
    name: '应用物理学',
    college: '理学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 60,
    rank: 153113,
    tags: ['多有色觉限制', '应用物理', '应用理科'],
    hotLevel: 3,
    description: '培养掌握应用物理学基本理论和实验技能，能在物理应用、光电技术、新材料等领域从事研发、应用的高级专门人才。',
    features: ['应用物理方向', '物理技术应用', '基础科学应用'],
    courses: [
      { semester: '第1学期', name: '高等数学、普通物理、普通化学' },
      { semester: '第2学期', name: '线性代数、数学物理方法' },
      { semester: '第3学期', name: '理论力学、电磁学' },
      { semester: '第4学期', name: '热力学与统计物理、量子力学' },
      { semester: '第5学期', name: '固体物理、光学' },
      { semester: '第6学期', name: '光电技术、半导体物理' },
      { semester: '第7学期', name: '专业实习、应用物理综合实验' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于光电企业、半导体企业、科研院所、检测机构。',
    teachers: '专业教师具有物理学研究背景。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },
  {
    id: 'water-supply',
    name: '给排水科学与工程',
    college: '土木工程学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 70,
    rank: 153113,
    tags: ['多有色觉限制', '给排水', '市政工程'],
    hotLevel: 3,
    description: '培养掌握给排水科学与工程基本理论和技术，能在市政给水排水、污水处理、建筑给排水等领域从事设计、施工、运行的高级工程技术人才。',
    features: ['给排水方向', '给水排水工程应用', '市政基础设施'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '工程制图、理论力学' },
      { semester: '第3学期', name: '材料力学、水力学' },
      { semester: '第4学期', name: '水文学与水文地质、水处理微生物' },
      { semester: '第5学期', name: '给水工程、排水工程' },
      { semester: '第6学期', name: '建筑给排水、水泵与水泵站' },
      { semester: '第7学期', name: '专业实习、给排水工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于市政工程企业、污水处理厂、建筑设计院、水务公司。',
    teachers: '专业教师具有给排水工程实践经验。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'textile-engineering',
    name: '纺织工程',
    college: '纺织服装学院',
    type: 'physics',
    minScore: 506,
    avgScore: 510,
    maxScore: 519,
    plan: 70,
    rank: 153113,
    tags: ['多有色觉限制', '纺织', '传统工科'],
    hotLevel: 3,
    description: '培养掌握纺织工程基本理论和技术，能在纺织企业、服装企业从事纺织工艺设计、生产管理、产品研发的高级工程技术人才。',
    features: ['纺织工程方向', '纺织工艺应用', '纺织服装产业'],
    courses: [
      { semester: '第1学期', name: '高等数学、大学物理、普通化学' },
      { semester: '第2学期', name: '有机化学、工程制图' },
      { semester: '第3学期', name: '纺织材料学、机械设计基础' },
      { semester: '第4学期', name: '纺纱学、织造学' },
      { semester: '第5学期', name: '针织学、纺织化学' },
      { semester: '第6学期', name: '染整工艺原理、非织造布' },
      { semester: '第7学期', name: '专业实习、纺织工程综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于纺织企业、服装企业、纺织机械厂、纺织贸易公司。',
    teachers: '专业教师具有纺织行业丰富经验。',
    salary: '毕业五年平均月薪约 5500-9500元'
  },

  // ========== 历史类 · 普通专业（9个） ==========
  {
    id: 'accounting-history',
    name: '会计学',
    college: '经济管理学院',
    type: 'history',
    minScore: 547,
    avgScore: 550,
    maxScore: 558,
    plan: 60,
    rank: 24650,
    tags: ['01专业组', '有色觉要求', '经管热门'],
    hotLevel: 5,
    description: '培养掌握会计学基本理论和方法，能在企事业单位、政府部门从事会计核算、财务管理、审计等工作的高级专门人才。',
    features: ['高分热门专业', '注册会计师方向', '稳定就业'],
    courses: [
      { semester: '第1学期', name: '管理学原理、基础会计、高等数学' },
      { semester: '第2学期', name: '经济学原理、统计学' },
      { semester: '第3学期', name: '中级财务会计、财务管理' },
      { semester: '第4学期', name: '成本会计、管理会计' },
      { semester: '第5学期', name: '高级财务会计、审计学' },
      { semester: '第6学期', name: '会计信息系统、财务分析' },
      { semester: '第7学期', name: '专业实习、会计综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '主要就业于各类企业、金融机构、会计师事务所、政府部门。',
    teachers: '专业教师具有丰富的会计实践经验。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'financial-management-history',
    name: '财务管理',
    college: '经济管理学院',
    type: 'history',
    minScore: 545,
    avgScore: 548,
    maxScore: 555,
    plan: 60,
    rank: 25583,
    tags: ['01专业组', '有色觉要求', '经管热门'],
    hotLevel: 5,
    description: '培养掌握财务管理基本理论和方法，能在企事业单位、金融机构从事财务核算、资金管理、投资分析的高级专门人才。',
    features: ['财务管理方向', '金融投资应用', '企业财务管理'],
    courses: [
      { semester: '第1学期', name: '管理学原理、基础会计、高等数学' },
      { semester: '第2学期', name: '微观经济学、统计学' },
      { semester: '第3学期', name: '中级财务会计、财务管理' },
      { semester: '第4学期', name: '投资学、金融学' },
      { semester: '第5学期', name: '高级财务管理、成本管理' },
      { semester: '第6学期', name: '财务分析、税务筹划' },
      { semester: '第7学期', name: '专业实习、财务综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于各类企业、银行、证券公司、投资机构。',
    teachers: '专业教师具有丰富的财务管理实践经验。',
    salary: '毕业五年平均月薪约 5500-10000元'
  },
  {
    id: 'chinese-language',
    name: '汉语言文学',
    college: '人文学院',
    type: 'history',
    minScore: 537,
    avgScore: 540,
    maxScore: 550,
    plan: 80,
    rank: 29352,
    tags: ['01专业组', '无限制', '文科热门'],
    hotLevel: 4,
    description: '培养掌握汉语言文学基本理论和知识，能在教育、文化、出版、党政机关等领域从事教学、研究、编辑、管理的高级专门人才。',
    features: ['汉语言文学方向', '文学研究与教学应用', '文化产业'],
    courses: [
      { semester: '第1学期', name: '文学概论、现代汉语、写作' },
      { semester: '第2学期', name: '古代汉语、中国古代文学' },
      { semester: '第3学期', name: '中国现当代文学、外国文学' },
      { semester: '第4学期', name: '文艺理论、语言学概论' },
      { semester: '第5学期', name: '美学、比较文学' },
      { semester: '第6学期', name: '应用写作、古典文献学' },
      { semester: '第7学期', name: '专业实习、文学研究综合' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于中小学、文化部门、出版机构、党政机关。',
    teachers: '专业教师具有深厚的文学研究背景。',
    salary: '毕业五年平均月薪约 5000-9500元'
  },
  {
    id: 'business-administration-history',
    name: '工商管理',
    college: '经济管理学院',
    type: 'history',
    minScore: 537,
    avgScore: 540,
    maxScore: 548,
    plan: 70,
    rank: 29352,
    tags: ['01专业组', '有色觉要求', '经管类'],
    hotLevel: 4,
    description: '培养掌握工商管理基本理论和方法，能在各类企业、事业单位从事经营管理、市场营销、人力资源管理等工作的高级专门人才。',
    features: ['企业管理方向', '综合管理技能', '广泛就业面'],
    courses: [
      { semester: '第1学期', name: '管理学原理、基础会计' },
      { semester: '第2学期', name: '微观经济学、统计学' },
      { semester: '第3学期', name: '市场营销、财务管理' },
      { semester: '第4学期', name: '组织行为学、人力资源管理' },
      { semester: '第5学期', name: '运营管理、战略管理' },
      { semester: '第6学期', name: '企业管理案例、商务谈判' },
      { semester: '第7学期', name: '专业实习、企业管理综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于各类企业、管理咨询公司、事业单位。',
    teachers: '专业教师具有企业管理实践经验。',
    salary: '毕业五年平均月薪约 5000-9500元'
  },
  {
    id: 'international-trade-history',
    name: '国际经济与贸易',
    college: '经济管理学院',
    type: 'history',
    minScore: 536,
    avgScore: 539,
    maxScore: 547,
    plan: 60,
    rank: 29840,
    tags: ['01专业组', '无限制', '经管类', '外贸'],
    hotLevel: 3,
    description: '培养掌握国际经济与贸易基本理论和技能，能在涉外经济贸易部门、外资企业、进出口企业从事业务和管理工作的高级专门人才。',
    features: ['国际贸易方向', '外语能力强', '外向型经济'],
    courses: [
      { semester: '第1学期', name: '英语、微观经济学' },
      { semester: '第2学期', name: '宏观经济学、国际贸易理论' },
      { semester: '第3学期', name: '统计学、国际贸易实务' },
      { semester: '第4学期', name: '金融学、国际金融' },
      { semester: '第5学期', name: '国际结算、外贸函电' },
      { semester: '第6学期', name: '国际商法、跨境电商' },
      { semester: '第7学期', name: '专业实习、外贸综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于外贸企业、外资企业、进出口公司、跨境电商企业。',
    teachers: '专业教师具有国际贸易实践经验。',
    salary: '毕业五年平均月薪约 5000-9500元'
  },
  {
    id: 'e-commerce-history',
    name: '电子商务',
    college: '经济管理学院',
    type: 'history',
    minScore: 535,
    avgScore: 538,
    maxScore: 546,
    plan: 60,
    rank: 30302,
    tags: ['01专业组', '无限制', '电商', '互联网+'],
    hotLevel: 4,
    description: '培养掌握电子商务基本理论和技能，能在电商企业、互联网企业、传统企业电商部门从事运营、营销、技术工作的高级专门人才。',
    features: ['电子商务方向', '网络营销应用', '互联网+时代热门'],
    courses: [
      { semester: '第1学期', name: '管理学原理、基础会计' },
      { semester: '第2学期', name: '电子商务概论、市场营销' },
      { semester: '第3学期', name: '网络营销、网页设计' },
      { semester: '第4学期', name: '电子商务运营、电商平台技术' },
      { semester: '第5学期', name: '跨境电商、电子商务数据分析' },
      { semester: '第6学期', name: '电商文案、电商法律' },
      { semester: '第7学期', name: '专业实习、电商项目实战' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于电子商务企业、互联网公司、跨境电商企业、传统企业电商部门。',
    teachers: '专业教师紧跟电子商务行业发展。',
    salary: '毕业五年平均月薪约 5000-9500元'
  },
  {
    id: 'english-history',
    name: '英语',
    college: '外国语学院',
    type: 'history',
    minScore: 535,
    avgScore: 538,
    maxScore: 546,
    plan: 70,
    rank: 30302,
    tags: ['01专业组', '仅招英语考生', '外语热门'],
    hotLevel: 4,
    description: '培养掌握英语语言文学基本理论和技能，能在教育、翻译、外贸、外企等领域从事英语教学、翻译、涉外工作的高级专门人才。',
    features: ['英语专业方向', '翻译与教学应用', '跨文化交流能力'],
    courses: [
      { semester: '第1学期', name: '基础英语、英语听力、英语口语' },
      { semester: '第2学期', name: '英语阅读、英语写作' },
      { semester: '第3学期', name: '高级英语、英语语法' },
      { semester: '第4学期', name: '英国文学、美国文学' },
      { semester: '第5学期', name: '翻译理论与实践、英语语言学' },
      { semester: '第6学期', name: '口译、英语教学法' },
      { semester: '第7学期', name: '专业实习、英语综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于中小学、培训机构、翻译公司、外贸企业、外资企业。',
    teachers: '专业教师具有海外留学和教学经验。',
    salary: '毕业五年平均月薪约 5000-9500元'
  },
  {
    id: 'japanese-history',
    name: '日语',
    college: '外国语学院',
    type: 'history',
    minScore: 533,
    avgScore: 536,
    maxScore: 544,
    plan: 60,
    rank: 31201,
    tags: ['01专业组', '招英语/日语考生', '外语'],
    hotLevel: 3,
    description: '培养掌握日语语言文学基本理论和技能，能在外企、外贸企业、教育机构从事日语翻译、教学、外贸业务的高级专门人才。',
    features: ['日语专业方向', '翻译与教学应用', '中日文化交流'],
    courses: [
      { semester: '第1学期', name: '基础日语、日语听力、日语口语' },
      { semester: '第2学期', name: '日语阅读、日语写作' },
      { semester: '第3学期', name: '高级日语、日语语法' },
      { semester: '第4学期', name: '日本文学、日本文化' },
      { semester: '第5学期', name: '翻译理论与实践、日语语言学' },
      { semester: '第6学期', name: '口译、日语教学法' },
      { semester: '第7学期', name: '专业实习、日语综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于日资企业、外贸企业、翻译公司、教育机构。',
    teachers: '专业教师具有日本留学和教学经验。',
    salary: '毕业五年平均月薪约 5000-9500元'
  },
  {
    id: 'tourism-management-history',
    name: '旅游管理',
    college: '经济管理学院',
    type: 'history',
    minScore: 533,
    avgScore: 536,
    maxScore: 544,
    plan: 60,
    rank: 31201,
    tags: ['01专业组', '无限制', '旅游', '服务管理'],
    hotLevel: 3,
    description: '培养掌握旅游管理基本理论和技能，能在旅游企业、酒店、景区从事旅游策划、酒店管理、景区管理的高级专门人才。',
    features: ['旅游管理方向', '旅游与酒店服务应用', '旅游产业'],
    courses: [
      { semester: '第1学期', name: '管理学原理、旅游学概论' },
      { semester: '第2学期', name: '经济学、旅游心理学' },
      { semester: '第3学期', name: '旅游市场营销、旅游经济学' },
      { semester: '第4学期', name: '酒店管理、旅游管理信息系统' },
      { semester: '第5学期', name: '旅游规划与开发、旅行社管理' },
      { semester: '第6学期', name: '景区管理、旅游英语' },
      { semester: '第7学期', name: '专业实习、旅游综合实训' },
      { semester: '第8学期', name: '毕业设计、就业指导' }
    ],
    employment: '就业于旅游企业、酒店、旅行社、景区管理部门。',
    teachers: '专业教师具有旅游管理行业经验。',
    salary: '毕业五年平均月薪约 5000-9000元'
  },

  // ========== 中外合作办学（3个） ==========
  {
    id: 'electrical-engineering-china-uk',
    name: '电气工程及其自动化（中英合作）',
    college: '电气与信息工程学院',
    type: 'physics',
    minScore: 500,
    avgScore: 505,
    maxScore: 520,
    plan: 60,
    rank: 161262,
    tags: ['中外合作', '中英合作', '英国格林威治大学', '大四英国就读'],
    hotLevel: 3,
    description: '培养掌握电气工程基本理论和专业知识，具有国际视野，能在电力系统、电气设备制造、新能源发电等领域从事设计、生产、管理的高级工程技术人才。大四赴英国格林威治大学就读。',
    features: ['中外合作办学', '中英双学位', '国际视野培养'],
    courses: [
      { semester: '第1-2年国内', name: '高等数学、大学物理、电路分析、电子技术' },
      { semester: '第3年国内', name: '电机与拖动、电力系统分析、自动控制原理' },
      { semester: '第4年英国', name: '英国格林威治大学专业课程' },
      { semester: '备注', name: '完成中英双方课程可获双学位' }
    ],
    employment: '毕业生广泛就业于国家电网、发电企业、电气设备制造企业、外资企业、科研院所，具有国际竞争力。',
    teachers: '中英双方师资共同授课，注重国际工程教育标准。',
    salary: '毕业五年平均月薪约 7000-15000元'
  },
  {
    id: 'mechanical-design-china-uk',
    name: '机械设计制造及其自动化（中英合作）',
    college: '机械工程学院',
    type: 'physics',
    minScore: 491,
    avgScore: 496,
    maxScore: 515,
    plan: 60,
    rank: 173224,
    tags: ['中外合作', '中英合作', '英国格林威治大学', '大四英国就读'],
    hotLevel: 3,
    description: '培养掌握机械设计制造基本理论和技术，具有国际视野，能在机械制造、装备设计、生产管理等领域从事设计、制造、管理的高级工程技术人才。大四赴英国格林威治大学就读。',
    features: ['中外合作办学', '中英双学位', '国际视野培养'],
    courses: [
      { semester: '第1-2年国内', name: '高等数学、大学物理、机械制图、理论力学' },
      { semester: '第3年国内', name: '材料力学、机械设计、机械制造技术' },
      { semester: '第4年英国', name: '英国格林威治大学专业课程' },
      { semester: '备注', name: '完成中英双方课程可获双学位' }
    ],
    employment: '就业于机械制造企业、装备制造企业、汽车企业、外资企业，具有国际竞争力。',
    teachers: '中英双方师资共同授课，注重国际工程教育标准。',
    salary: '毕业五年平均月薪约 6000-13000元'
  },
  {
    id: 'vehicle-engineering-china-us',
    name: '车辆工程（中美合作）',
    college: '机械工程学院',
    type: 'physics',
    minScore: 484,
    avgScore: 489,
    maxScore: 510,
    plan: 60,
    rank: 182031,
    tags: ['中外合作', '中美合作', '美国底特律大学', '大四五美国就读'],
    hotLevel: 3,
    description: '培养掌握车辆工程基本理论和技术，具有国际视野，能在汽车设计、汽车制造、汽车电子等领域从事研发、生产的高级工程技术人才。大四、大五赴美国底特律大学就读。',
    features: ['中外合作办学', '中美双学位', '国际视野培养', '美国汽车城学习'],
    courses: [
      { semester: '第1-3年国内', name: '高等数学、大学物理、机械制图、汽车构造' },
      { semester: '第3年国内', name: '汽车理论、汽车设计、汽车电子技术' },
      { semester: '第4-5年美国', name: '美国底特律大学专业课程' },
      { semester: '备注', name: '完成中美双方课程可获双学位' }
    ],
    employment: '就业于汽车制造企业、汽车零部件企业、汽车研发机构、外资汽车企业，具有国际竞争力。',
    teachers: '中美双方师资共同授课，底特律大学为美国汽车城知名高校。',
    salary: '毕业五年平均月薪约 7000-15000元'
  }
];